baseURL: https://alism.ir
languageCode: en
title: Ali Motlagh
theme: PaperMod




disqusShortname: alism-1


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

pygmentsUseClasses: true

#googleAnalytics: G-4XL1C0F7HT


defaultContentLanguage: en
languages:

  fa:
    languagedirection: rtl
    languageAltTitle: "فارسی"
    title: علی مطلق
    weight: 2
    copyright: "اینجا کپی رایت معنی نداره؛ لطفا اگه کپی می کنید، حداقل یه لینک بدید."
    menu:
      main:
        - identifier: home
          name: خانه
          url: /
          weight: 10
        - identifier: services
          name: خدمات
          url: /services/
          weight: 20
        - identifier: posts
          name: بلاگ
          url: /posts/
          weight: 50
        - identifier: about
          name: دربارهٔ من 
          url: /about/
          weight: 60
        - identifier: tags
          name:  تگ‌ها 
          url: /tags/
          weight: 70
        - identifier: archives
          name: آرشیو
          url: /archives/
          weight: 80

    params:
      author: 'علی مطلق'
      #description: Tesla's Awesome Hugo Site
      label:
        text: "علی مطلق" 
        #icon: "/assets/images/favicon.ico"
        #iconHeight: 32
      # profile-mode
      CustomProfileMode:
      ProfileMode:
        enabled: true
        title: "علی هستم"  # optional default will be site title
        subtitle:  کنیبالیزیشن یا هم نوع خواری وقتی است که صفحات یک سایت با هم به رقابت می‌پردازند و باعث افت رتبه کلمات کلیدی یکدیگر می‌شوند. در این نوشته با نحوه تشخیص همنوع خواری و همچنین نحوه رفع آن آشنا می‌شوید.
        imageUrl: "/assets/images/alish.jpg" # optional
        imageTitle: "Ali Shahcheraghi" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: طراحی سایت
            url: "https://webshark.ir/web-design/"
          - name: سئو و بهینه‌سازی
            url: "https://webshark.ir/seo-service/"

      # home-info mode
      #homeInfoParams:
      #  Title: "علی هستم"
      #  Content: " به زودی اینجا یه چیزی در مورد خودم مینویسم


      
      comments: true
      ShowShareButtons: true
      ShowCodeCopyButtons: true
      #hideSummary: true
      ShowBreadCrumbs: true


      socialIcons:
        - name: "key"
          url: "/0xF5249EF4E609DC00.asc"
        - name: "email"
          url: "mailto:alish@outlook.at"
        - name: "rss"
          url: "index.xml"
        - name: "twitter"
          url: "#"
        - name: "github"
          url: "https://github.com/amotlagh"
        - name: "linkedin"
          url: "#"


  en:
    languageAltTitle: "English"
    title: Ali Motlagh
    weight: 1
    #copyright: " "
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: about
          name: About
          url: /about/
          weight: 20
        - identifier: work
          name: Work
          url: /work/
          weight: 10
    params:
      comments: false
      author: Ali Motlagh
      #description: Tesla's Awesome Hugo Site
      label:
        text: "Ali."
        #icon: "/assets/images/favicon.ico"
        #iconHeight: 35
      profileMode:
        enabled: true
        title: "Hi, I'm Ali." # optional default will be site title
        subtitle: "Freelance Web Designer & Developer based in Shiraz, Iran.
Highly experienced in designing & developing custom Wordpress websites."
        imageUrl: "/assets/images/alish.jpg" # optional
        imageTitle: "Ali Shahcheraghi" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size


      socialIcons: # optional
        - name: "linkedin"
          url: "#"
        - name: "github"
          url: "https://github.com/amotlagh"
        - name: "rss"
          url: "index.xml"
        - name: "twitter"
          url: "#"
        - name: "email"
          url: "mailto:alish@outlook.at"
        - name: "key"
          url: "/0xF5249EF4E609DC00.asc"









params:
  env: production
  hideMeta: true
  defaultTheme: auto
  navigation:
    help: Help
  assets:
    disableFingerprinting: true
    favicon: "/assets/images/favicon.ico"
    favicon16x16:  "/assets/images/favicon-16x16.png"
    favicon32x32:  "/assets/images/favicon-32x32.png"
    apple_touch_icon:  "/assets/images/apple-touch-icon.png"
    safari_pinned_tab:  "/assets/images/safari-pinned-tab.svg"
  #disableScrollToTop: true
  #ShowRssButtonInSectionTermList: true
  ShowToc: true
  TocOpen: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  cover:
    linkFullImages: false
    relative: true
    hiddenInList: false
    responsiveImages: true


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
        
        



markup:
  goldmark:
    renderer:
      unsafe: true
