baseURL: https://alism.ir/
languageCode: en
title: Ali Motlagh
theme: PaperMod
defaultContentLanguageInSubdir: true
disableHugoGeneratorInject: true



disqusShortname: alism-1


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

pygmentsUseClasses: true

#googleAnalytics: G-4XL1C0F7HT


defaultContentLanguage: en
languages:

  fa:
    languagedirection: rtl
    languageAltTitle: "فارسی"
    languageName: فارسی
    title: علی مطلق
    weight: 2
    copyright: "لطفا اگه کپی می کنید، حداقل یه لینک بدید."
    menu:
      main:
        - identifier: home
          name: خانه
          url: /fa/
          weight: 10
        - identifier: web-design
          name: طراحی سایت
          url: /fa/web-design/
          weight: 20
        - identifier: seo
          name: خدمات سئو
          url: /fa/seo/
          weight: 30
        - identifier: services
          name: سایر خدمات
          url: /fa/services/
          weight: 40         
        - identifier: posts
          name: بلاگ
          url: /fa/posts/
          weight: 50
        - identifier: about
          name: دربارهٔ من
          url: /fa/about/
          weight: 70        


    params:
      author: 'علی مطلق'
      #description: Tesla's Awesome Hugo Site
      label:
        text: "علی مطلق" 
        #icon: "/assets/images/favicon.ico"
        #iconHeight: 32
      # profile-mode
      ProfileMode:
        enabled: false
        title: Ali Motlagh  # optional default will be site title
        subtitle: Front-End and WordPress Developer
        imageUrl: "/assets/images/alish.jpg" # optional
        imageTitle: "Ali Shahcheraghi" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        #buttons:
        #  - name: طراحی سایت
        #    url: "/fa/web-design/"
        #  - name: سئو و بهینه‌سازی
        #    url: "/fa/seo/"

      # home-info mode
      homeInfoParams:
        Title: "علی مطلق"
        Content: "پر شور و شوق در مورد مهندسی نرم‌افزار، استارتاپ‌ها و راهبری."

      mainSections:
        - posts
        - seo
        - services


      
      comments: false
      ShowShareButtons: true
      ShowCodeCopyButtons: true
      #hideSummary: true
      ShowBreadCrumbs: true
      ShowRelatedContent: true


      socialIcons:
        - name: "key"
          url: "/0xF5249EF4E609DC00.asc"
        - name: "email"
          url: "mailto:alimotlagh@protonmail.com"
        - name: "rss"
          url: "index.xml"
        - name: "twitter"
          url: "#"
        - name: "github"
          url: "https://github.com/amotlagh"
        - name: "linkedin"
          url: "#"


  en:
    languageAltTitle: "English"
    languageName: English
    title: Ali Motlagh
    weight: 1
    #copyright: " "
    menu:
      main:
        - identifier: services
          name: Services
          url: /en/services/
          weight: 5
        - identifier: about
          name: About
          url: /en/about/
          weight: 20
        - identifier: work
          name: Works
          url: /en/works/
          weight: 10
    params:
      comments: false
      author: Ali Motlagh
      #description: Tesla's Awesome Hugo Site
      label:
        text: "Ali."
        #icon: "/assets/images/favicon.ico"
        #iconHeight: 35
      profileMode:
        enabled: false
        title: "Hi, I'm Ali." # optional default will be site title
        subtitle: "Freelance Web Designer & Developer based in Shiraz, Iran.
Highly experienced in designing & developing custom Wordpress websites."
        imageUrl: "/assets/images/alish.jpg" # optional
        imageTitle: "Ali Shahcheraghi" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size

      # home-info mode
      homeInfoParams:
        Title: "Hi, I'm Ali."
        Content: "Freelance Web Designer & Developer based in Shiraz, Iran. Highly experienced in designing & developing custom Wordpress websites."


      socialIcons: # optional
        - name: "linkedin"
          url: "#"
        - name: "github"
          url: "https://github.com/amotlagh"
        - name: "rss"
          url: "index.xml"
        - name: "twitter"
          url: "#"
        - name: "email"
          url: "mailto:alish@outlook.at"
        - name: "key"
          url: "/0xF5249EF4E609DC00.asc"









params:
  env: production
  hideMeta: true
  defaultTheme: auto
  navigation:
    help: Help
  assets:
    theme_color: '#121417'
    msapplication_TileColor: '#121417'
    disableHLJS: true
    disableFingerprinting: true
    favicon: "/assets/images/favicon.ico"
    favicon16x16:  "/assets/images/favicon-16x16.png"
    favicon32x32:  "/assets/images/favicon-32x32.png"
    apple_touch_icon:  "/assets/images/apple-touch-icon.png"
    safari_pinned_tab:  "/assets/images/safari-pinned-tab.svg"
  #disableScrollToTop: true
  #ShowRssButtonInSectionTermList: true
  ShowToc: true
  TocOpen: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  cover:
    linkFullImages: false
    relative: true
    hiddenInList: false
    responsiveImages: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
        
        
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"] ##  can be less but not more than shown in list


markup:
  goldmark:
    renderer:
      unsafe: true
    

sitemap:
  changefreq: weekly
  filename: sitemap.xml